
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/lib/types/database';

const SUPABASE_URL = "https://hcrjkziycryuugzbixhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhjcmpreml5Y3J5dXVnemJpeGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTYxNTYsImV4cCI6MjA3MDU5MjE1Nn0.9qEuhEgeLdWqCcCqp0kMZGROMwMeAA5cKsU5qZpl7Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
